services:
  prod:
    image: detectit_frontend_production
    container_name: detectit_frontend_production
    restart: always
    build:
      context: .
      target: builder
    ports:
      - "3000:3000"
    command: serve -s dist -l 3000
